name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          VERSION=$(git describe --always --dirty --tags)
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: make build

      - name: Make tarball
        run: |
          tar -czf rada_${{ env.VERSION }}.tar.gz \
            -C . CHANGELOG.md \
            -C . LICENSE \
            -C . README.md \
            -C .build/release rada

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: rada_${{ env.VERSION }}.tar.gz
          archive: false
